/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-12 15:15:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product.top;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class topDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS here -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/slicknav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/animate.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/fontawesome-all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/slick.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- slider Area Start-->\r\n");
      out.write("\t<div class=\"slider-area \">\r\n");
      out.write("\t\t<!-- Mobile Menu -->\r\n");
      out.write("\t\t<div class=\"single-slider slider-height2 d-flex align-items-center\"\r\n");
      out.write("\t\t\tdata-background=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/img/hero/category.jpg\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xl-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"hero-cap text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>product Details</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- slider Area End-->\r\n");
      out.write("\r\n");
      out.write("\t<!--================Single Product Area =================-->\r\n");
      out.write("\t<div class=\"product_image_area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product_img_slide owl-carousel\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single_product_img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cloth.cimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"#\" class=\"img-fluid\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"single_product_text text-center\">\r\n");
      out.write("\t\t\t\t\t\t<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cloth.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cloth.detail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card_area\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product_count_area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Quantity</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product_count d-inline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"product_count_item inumber-decrement\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <i\tclass=\"ti-minus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"product_count_item input-number\" type=\"text\" value=\"1\" min=\"0\" max=\"10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <span class=\"product_count_item number-increment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <i class=\"ti-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cloth.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p> <!-- 지금은 1개의 가격만 표시... 카트테이블과 합쳐 total금액으로 나와야 할 듯..... -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"add_to_cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn_3\">add to cart</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--================End Single Product Area =================-->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 하단 부분은 지워도 될 듯..... -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- subscribe part here -->\r\n");
      out.write("\t<section class=\"subscribe_part section_padding\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"subscribe_part_content\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Get promotions & updates!</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Seamlessly empower fully researched growth strategies and\r\n");
      out.write("\t\t\t\t\t\t\tinteroperable internal or “organic” sources credibly innovate\r\n");
      out.write("\t\t\t\t\t\t\tgranular internal .</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"subscribe_form\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" placeholder=\"Enter your mail\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"btn_1\">Subscribe</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- subscribe part end -->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- JS here -->\r\n");
      out.write("\t<!-- All JS Custom Plugins Link Here here -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Jquery Mobile Menu -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- One Page, Animated-HeadLin -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/wow.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/animated.headline.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scrollup, nice-select, sticky -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- contact js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/contact.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.form.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/mail-script.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Jquery Plugins, main Jquery -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/plugins.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- swiper js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/swiper.min.js\"></script>\r\n");
      out.write("\t<!-- swiper js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/mixitup.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/waypoints.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
