/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-12 15:13:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class noticeModifyForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/include/footer_js.jsp", Long.valueOf(1601339508000L));
    _jspx_dependants.put("/WEB-INF/views/summernote/summernote.jsp", Long.valueOf(1601367060000L));
    _jspx_dependants.put("/WEB-INF/views/include/open_footer.jsp", Long.valueOf(1601367508000L));
    _jspx_dependants.put("/WEB-INF/views/include/open_header.jsp", Long.valueOf(1601367450000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("    \t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("        <title>eCommerce HTML-5 Template </title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- CSS here -->\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/bootstrap.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/owl.carousel.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/flaticon.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/slicknav.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/animate.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/magnific-popup.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/fontawesome-all.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/themify-icons.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/slick.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/nice-select.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- summernote -->\r\n");
      out.write("\t\t\t<link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/summernote/summernote.min.css\" rel=\"stylesheet\">\r\n");
      out.write("   </head>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.latest-product-area{padding-bottom:0px;}\r\n");
      out.write("\t\tfooter{border-top:solid 1px black;}\r\n");
      out.write("\t</style>\r\n");
      out.write("   <body>\r\n");
      out.write("  \r\n");
      out.write("<section class=\"content container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div class=\"card card-outline card-info\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-header row\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"col-md-8\">공지 수정</h4>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"float-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-warning\" id=\"modifyBtn\">수 정</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default \" id=\"cancelBtn\">취 소</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div><!--end card-header  -->\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<form role=\"form\" method=\"post\" action=\"noticeModify.do\" name=\"noticeModifyForm\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"title\">제 목</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"title\" name='title' class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"title\">번호</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"nno\" name='nno' class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.nno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"writer\">작성자</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"writer\" readonly\tname=\"writer\" class=\"form-control\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"content\">내 용</label>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\" id=\"content\" rows=\"3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"500자 내외로 작성하세요.\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div><!--end card-body  -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div><!-- end card -->\t\t\t\t\r\n");
      out.write("\t\t\t</div><!-- end col-md-12 -->\r\n");
      out.write("\t\t</div><!-- end row -->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- /.content -->\r\n");
      out.write("    <script>\r\n");
      out.write("\t$('#modifyBtn').on('click',function(e){\t\t\t\t\r\n");
      out.write("\t\tvar title=$('input[name=\"title\"]');\r\n");
      out.write("\t\tif(title.val()==\"\"){\r\n");
      out.write("\t\t\talert(\"제목은 필수입니다.\");\t\t\t\r\n");
      out.write("\t\t\ttitle.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar form=document.noticeModifyForm;\t\t\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#cancelBtn').on('click',function(e){\r\n");
      out.write("\t\thistory.go(-1);\r\n");
      out.write("\t});\r\n");
      out.write("</script>  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#content').summernote({\r\n");
      out.write("\t\tplaceholder:'여기에 내용을 적으세요.',\r\n");
      out.write("\t\theight:250,\r\n");
      out.write("\t\tdisableResizeEditor: true,\r\n");
      out.write("\t\tcallbacks:{\r\n");
      out.write("\t\t\tonImageUpload : function(files, editor, welEditable) {\r\n");
      out.write("\t\t\t\t//file size check!\r\n");
      out.write("\t\t\t\tfor (var i = files.length - 1; i >= 0; i--) {\r\n");
      out.write("\t\t\t\t\tif(files[i].size > 1024*1024*5){\r\n");
      out.write("\t            \t\talert(\"이미지는 5MB 미만입니다.\");\r\n");
      out.write("\t            \t\treturn;\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//file sending\r\n");
      out.write("\t\t\t\tfor (var i = files.length - 1; i >= 0; i--) {\r\n");
      out.write("\t            \tsendFile(files[i], this);\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonMediaDelete : function(target) {\r\n");
      out.write("\t\t\t\tvar answer=confirm(\"정말 이미지를 삭제하시겠습니다.\");\r\n");
      out.write("\t\t\t\tif(answer){\r\n");
      out.write("\t\t\t\t\tdeleteFile(target[0].src);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function sendFile(file, el) {\r\n");
      out.write("\t\r\n");
      out.write("\tvar form_data = new FormData();\r\n");
      out.write("\tform_data.append(\"file\", file); \r\n");
      out.write("\t$.ajax({\r\n");
      out.write("    \tdata: form_data,\r\n");
      out.write("    \ttype: \"POST\",\r\n");
      out.write("    \turl: '");
      out.print(request.getContextPath());
      out.write("/uploadImg.do',\r\n");
      out.write("    \tcache: false,\r\n");
      out.write("    \tcontentType: false,\t    \t\r\n");
      out.write("    \tprocessData: false,\r\n");
      out.write("    \tsuccess: function(img_url) {\r\n");
      out.write("      \t\t$(el).summernote('editor.insertImage', img_url);\r\n");
      out.write("    \t}\r\n");
      out.write("  \t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteFile(src) {\r\n");
      out.write("\t\r\n");
      out.write("\tvar splitSrc= src.split(\"=\");\r\n");
      out.write("\tvar fileName = splitSrc[splitSrc.length-1];\r\n");
      out.write("    \r\n");
      out.write("\t//alert(fileName);\r\n");
      out.write("\tvar fileData = {\r\n");
      out.write("\t\t\tfileName:fileName\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/deleteImg.do\",\r\n");
      out.write("\t\tdata : JSON.stringify(fileData),\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\tsuccess:function(res){\r\n");
      out.write("\t\t\tconsole.log(res);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("<!-- JS here -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- All JS Custom Plugins Link Here here -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("\t\t<!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/popper.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t    <!-- Jquery Mobile Menu -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- One Page, Animated-HeadLin -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/wow.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/animated.headline.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Scrollup, nice-select, sticky -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <!-- contact js -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/contact.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.form.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/mail-script.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("\t\t<!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/main.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/common.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/summernote/summernote.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- 기본 Jquery삽입 -->\r\n");
      out.write("        ");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.6/handlebars.min.js\" ></script>\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"subMenu-list-template\" >\r\n");
      out.write("{{#each .}}\r\n");
      out.write("\t<li class=\"nav-item subMenu\" >\r\n");
      out.write("      \t<a href=\"javascript:goPage('{{murl}}','{{mcode}}')\" class=\"nav-link\">\r\n");
      out.write("          <i class=\"{{micon}}\"></i>\r\n");
      out.write("             <p>{{mname }}</p>\r\n");
      out.write("        </a>\r\n");
      out.write("\t</li>\r\n");
      out.write("{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var printData=function(subMenuArr,target,templateObject){\r\n");
      out.write("\tvar template=Handlebars.compile(templateObject.html());\r\n");
      out.write("\tvar html = template(subMenuArr);\t\r\n");
      out.write("\t$('.subMenu').remove();\r\n");
      out.write("\ttarget.append(html);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function goPage(url, mCode){\r\n");
      out.write("\t// HTML5 지원브라우저에서 사용가능\r\n");
      out.write("\tif(typeof(history.pushState)=='function'){\r\n");
      out.write("\t\t// 현재 주소를 가져온다.\r\n");
      out.write("\t\tvar renewURL = location.href;\r\n");
      out.write("\t\t// 현재 주소중 .do 뒤 부분이 있다면 날려버린다.\r\n");
      out.write("\t\trenewURL = renewURL.substring(0, renewURL.indexOf(\".do\")+3);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(mCode != 'M000000'){\r\n");
      out.write("\t\t\trenewURL += \"?mCode=\"+mCode;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\thistory.pushState(mCode,null,renewURL);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tlocation.hash = \"#\"+mCode;\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#if_list').attr(\"src\",\"");
      out.print(request.getContextPath());
      out.write("\"+url);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goPageMain(url){\r\n");
      out.write("\t   // HTML5 지원브라우저에서 사용가능\r\n");
      out.write("\t   if(typeof(history.pushState)=='function'){\r\n");
      out.write("\t      // 현재 주소를 가져온다.\r\n");
      out.write("\t      var renewURL = location.href;\r\n");
      out.write("\t      // 현재 주소중 .do 뒤 부분이 있다면 날려버린다.\r\n");
      out.write("\t      renewURL = renewURL.substring(0, renewURL.indexOf(\".do\")+3);      \r\n");
      out.write("\t      \r\n");
      out.write("\t      \r\n");
      out.write("\t      history.pushState(null, renewURL);\r\n");
      out.write("\t   }\r\n");
      out.write("\t   $('#if_list').attr(\"src\",\"");
      out.print(request.getContextPath());
      out.write("\"+url);\r\n");
      out.write("\t   \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction calcHeight(){\r\n");
      out.write("\t   //find the height of the internal page\r\n");
      out.write("\t   \r\n");
      out.write("\t   var the_height=\r\n");
      out.write("\t   document.getElementById('if_list').contentWindow.document.body.scrollHeight;\r\n");
      out.write("\t   \r\n");
      out.write("\t   //change the height of the iframe\r\n");
      out.write("\t   $('#if_list_div').css(\"height\",the_height);\r\n");
      out.write("\t   \r\n");
      out.write("\t   //document.getElementById('the_iframe').scrolling = \"no\";\r\n");
      out.write("\t   document.getElementById('if_list').style.overflow = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tgoPage('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.murl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.mcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
