/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-12 15:13:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class noticeDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/include/footer_js.jsp", Long.valueOf(1601339508000L));
    _jspx_dependants.put("/WEB-INF/views/notice/notice_js_jsy.jsp", Long.valueOf(1601431404000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1601339508000L));
    _jspx_dependants.put("/WEB-INF/views/include/open_footer.jsp", Long.valueOf(1601367508000L));
    _jspx_dependants.put("/WEB-INF/views/include/open_header.jsp", Long.valueOf(1601367450000L));
    _jspx_dependants.put("jar:file:/C:/soo/A_TeachingMaterial/6.JspSpring/workspace/JSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Semi_Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("    \t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("        <title>eCommerce HTML-5 Template </title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- CSS here -->\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/bootstrap.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/owl.carousel.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/flaticon.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/slicknav.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/animate.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/magnific-popup.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/fontawesome-all.min.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/themify-icons.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/slick.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/nice-select.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- summernote -->\r\n");
      out.write("\t\t\t<link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/summernote/summernote.min.css\" rel=\"stylesheet\">\r\n");
      out.write("   </head>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.latest-product-area{padding-bottom:0px;}\r\n");
      out.write("\t\tfooter{border-top:solid 1px black;}\r\n");
      out.write("\t</style>\r\n");
      out.write("   <body>\r\n");
      out.write("  \r\n");
      out.write("<!-- Main content -->\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t<h3 class=\"card-title\">상세보기</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<label for=\"title\">제 목</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"title\" readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"writer\">번호</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"nno\" readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.nno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"writer\">작성자</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"writer\" readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"regDate\">작성일</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"regDate\" \r\n");
      out.write("\t\t\t\t\t\treadonly value=\"");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"viewcnt\">조회수</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"viewcnt\" readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.viewcnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"content\">내 용</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"content\" id=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- cardbody -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end col-md-12 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end row  -->\r\n");
      out.write("\t<button type=\"button\" id=\"modifyBtn\" name=\"modifyBtn\" class=\"genric-btn success circle\">수정</button>\t\r\n");
      out.write("\t<button type=\"button\" id=\"removeBtn\" name=\"removeBtn\"class=\"genric-btn danger circle\">삭제</button>\t\r\n");
      out.write("\t<button type=\"button\" id=\"listBtn\" name=\"listBtn\" class=\"genric-btn primary circle\">닫기</button>\t\r\n");
      out.write("\r\n");
      out.write("<form role=\"form\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"nno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.nno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var formObj = $(\"form[role='form']\");\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#registBtn').on('click',function(e){\r\n");
      out.write("\t//alert(\"regist btn click\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar form=document.registForm;\r\n");
      out.write("\t\r\n");
      out.write("\tif(form.title.value==\"\"){\r\n");
      out.write("\t\talert(\"제목은 필수입니다.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tform.submit();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('button#modifyBtn').on('click',function(evnet){\r\n");
      out.write("\t//alert(\"modify click\");\r\n");
      out.write("\tformObj.attr({\r\n");
      out.write("\t\t'action':'noticeModifyForm.do',\r\n");
      out.write("\t\t'method':'post'\r\n");
      out.write("\t});\r\n");
      out.write("\tformObj.submit();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#cancelBtn').on('click',function(e){\r\n");
      out.write("\thistory.go(-1);\r\n");
      out.write("});\r\n");
      out.write(" \r\n");
      out.write("$(\"#removeBtn\").on(\"click\", function(){\r\n");
      out.write("\t//alert(\"remove click\");\r\n");
      out.write("\tvar answer = confirm(\"정말 삭제하시겠습니까?\");\r\n");
      out.write("\tif(answer){\t\t\r\n");
      out.write("\t\tformObj.attr(\"action\", \"noticeRemove.do\");\r\n");
      out.write("\t\tformObj.attr(\"method\", \"post\");\r\n");
      out.write("\t\tformObj.submit();\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("$(\"#listBtn\").on(\"click\", function(){\r\n");
      out.write("\t//alert(\"list click\");\r\n");
      out.write("\twindow.opener.location.reload(true);\r\n");
      out.write("\twindow.close();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("<!-- JS here -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- All JS Custom Plugins Link Here here -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("\t\t<!-- Jquery, Popper, Bootstrap -->\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/popper.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t    <!-- Jquery Mobile Menu -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Jquery Slick , Owl-Carousel Plugins -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- One Page, Animated-HeadLin -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/wow.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/animated.headline.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Scrollup, nice-select, sticky -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.sticky.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <!-- contact js -->\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/contact.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.form.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/mail-script.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("\t\t<!-- Jquery Plugins, main Jquery -->\t\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/assets/js/main.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/common.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/summernote/summernote.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- 기본 Jquery삽입 -->\r\n");
      out.write("        ");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.6/handlebars.min.js\" ></script>\r\n");
      out.write("<script type=\"text/x-handlebars-template\"  id=\"subMenu-list-template\" >\r\n");
      out.write("{{#each .}}\r\n");
      out.write("\t<li class=\"nav-item subMenu\" >\r\n");
      out.write("      \t<a href=\"javascript:goPage('{{murl}}','{{mcode}}')\" class=\"nav-link\">\r\n");
      out.write("          <i class=\"{{micon}}\"></i>\r\n");
      out.write("             <p>{{mname }}</p>\r\n");
      out.write("        </a>\r\n");
      out.write("\t</li>\r\n");
      out.write("{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var printData=function(subMenuArr,target,templateObject){\r\n");
      out.write("\tvar template=Handlebars.compile(templateObject.html());\r\n");
      out.write("\tvar html = template(subMenuArr);\t\r\n");
      out.write("\t$('.subMenu').remove();\r\n");
      out.write("\ttarget.append(html);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function goPage(url, mCode){\r\n");
      out.write("\t// HTML5 지원브라우저에서 사용가능\r\n");
      out.write("\tif(typeof(history.pushState)=='function'){\r\n");
      out.write("\t\t// 현재 주소를 가져온다.\r\n");
      out.write("\t\tvar renewURL = location.href;\r\n");
      out.write("\t\t// 현재 주소중 .do 뒤 부분이 있다면 날려버린다.\r\n");
      out.write("\t\trenewURL = renewURL.substring(0, renewURL.indexOf(\".do\")+3);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(mCode != 'M000000'){\r\n");
      out.write("\t\t\trenewURL += \"?mCode=\"+mCode;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\thistory.pushState(mCode,null,renewURL);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tlocation.hash = \"#\"+mCode;\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#if_list').attr(\"src\",\"");
      out.print(request.getContextPath());
      out.write("\"+url);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goPageMain(url){\r\n");
      out.write("\t   // HTML5 지원브라우저에서 사용가능\r\n");
      out.write("\t   if(typeof(history.pushState)=='function'){\r\n");
      out.write("\t      // 현재 주소를 가져온다.\r\n");
      out.write("\t      var renewURL = location.href;\r\n");
      out.write("\t      // 현재 주소중 .do 뒤 부분이 있다면 날려버린다.\r\n");
      out.write("\t      renewURL = renewURL.substring(0, renewURL.indexOf(\".do\")+3);      \r\n");
      out.write("\t      \r\n");
      out.write("\t      \r\n");
      out.write("\t      history.pushState(null, renewURL);\r\n");
      out.write("\t   }\r\n");
      out.write("\t   $('#if_list').attr(\"src\",\"");
      out.print(request.getContextPath());
      out.write("\"+url);\r\n");
      out.write("\t   \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction calcHeight(){\r\n");
      out.write("\t   //find the height of the internal page\r\n");
      out.write("\t   \r\n");
      out.write("\t   var the_height=\r\n");
      out.write("\t   document.getElementById('if_list').contentWindow.document.body.scrollHeight;\r\n");
      out.write("\t   \r\n");
      out.write("\t   //change the height of the iframe\r\n");
      out.write("\t   $('#if_list_div').css(\"height\",the_height);\r\n");
      out.write("\t   \r\n");
      out.write("\t   //document.getElementById('the_iframe').scrolling = \"no\";\r\n");
      out.write("\t   document.getElementById('if_list').style.overflow = \"hidden\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tgoPage('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.murl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.mcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/notice/noticeDetail.jsp(36,22) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.regDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/notice/noticeDetail.jsp(36,22) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
